default: &default
  adapter: postgresql
  username: postgres
  password: 123456
  host: localhost
  port: 5432
  encoding: unicode
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: tradeview_development
production:
  <<: *default
  database: tradeview_development
 